apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-ingress
  namespace: canary-ns
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
    nginx.ingress.kubernetes.io/canary-by-header: "X-Canary"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* \.(js|css|svg|ico)$ {
        types {
          application/javascript js;
          text/css css;
          image/svg+xml svg;
          image/x-icon ico;
        }
        add_header Cache-Control "public, max-age=31536000, immutable";
      }
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: online-shop-v2
            port:
              number: 80
