apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache-green
  name: apache-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apache-green
  template:
    metadata:
      labels:
        app: apache-green
    spec:
      containers:
      - image: httpd
        name: apache-green
---
apiVersion: v1
kind: Service
metadata:
  name: apache-green-deployment-service
spec:
  selector:
    app: apache-green
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
