apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-blue
  name: nginx-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-blue
  template:
    metadata:
      labels:
        app: nginx-blue
    spec:
      containers:
      - image: nginx
        name: nginx-blue
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-blue-deployment-service
spec:
  selector:
    app: nginx-blue
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
