apiVersion: v1
kind: Service
metadata:
  name: recreate-service
  namespace: recreate-ns
spec:
  selector:
    app: online-shop
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000