apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary
    track: stable
  name: canary-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
        track: stable
    spec:
      containers:
      - image: nginx
        name: canary-nginx
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: canary-deployment-service
spec:
  selector:
    app: canary
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
