apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary
  name: canary-online-shop-v2 # This is the name of the deployment, should be different from the other deployment file
  namespace: canary-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - image: amitabhdevops/online_shop
        name: canary-online-shop
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"


